# Generated by Django 3.2.8 on 2022-03-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
            },
        ),
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ОВЗ')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Инвалидность',
                'verbose_name_plural': 'Инвалидности',
            },
        ),
        migrations.CreateModel(
            name='TerAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тер. управление')),
            ],
            options={
                'verbose_name': 'Тер. управление',
                'verbose_name_plural': 'Тер. управления',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('name', models.CharField(max_length=100, verbose_name='Название школы')),
                ('specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уклон школы')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='users.city', verbose_name='Город')),
                ('school_coordinator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinated_schools', to=settings.AUTH_USER_MODEL, verbose_name='Педагог-навигатор')),
                ('ter_administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='users.teradministration', verbose_name='Тер. управление')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='disability_types',
            field=models.ManyToManyField(blank=True, to='users.DisabilityType', verbose_name='ОВЗ'),
        ),
    ]
