# Generated by Django 3.2.8 on 2022-03-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220313_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ST', 'Школьник'), ('CO', 'Представитель ЦО'), ('TCH', 'Преподователь')], max_length=3, null=True, verbose_name='Роль'),
        ),
    ]
