# Generated by Django 3.2.8 on 2022-03-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220320_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='users.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ter_administration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='users.teradministration', verbose_name='Тер. управление'),
        ),
    ]
