# Generated by Django 3.2.8 on 2022-03-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220320_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities_schools', to='users.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ter_administration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adm_schools', to='users.teradministration', verbose_name='Тер. управление'),
        ),
    ]
