# Generated by Django 3.2.8 on 2022-03-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220321_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relocate_status',
            field=models.CharField(choices=[('NOT', 'Неперенесённый'), ('NLOG', 'Немавторизовался'), ('LOG', 'Авторизовался')], default='NOT', max_length=4, verbose_name='Статус переноса'),
        ),
    ]
