# Generated by Django 3.2.8 on 2022-03-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_centers', '0002_auto_20220313_2228'),
        ('users', '0002_auto_20220313_2228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название набора')),
                ('competencies', models.ManyToManyField(blank=True, related_name='voc_guid_bundle', to='education_centers.Competence', verbose_name='Компетенции')),
            ],
            options={
                'verbose_name': 'Набор проб',
                'verbose_name_plural': 'Наборы проб',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_limit', models.IntegerField(default=10, verbose_name='Максимальное кол-во участников')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schedule.bundle', verbose_name='Бандл')),
                ('participants', models.ManyToManyField(related_name='training_groups', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('school', models.ManyToManyField(related_name='groups', to='users.School', verbose_name='Школы')),
            ],
            options={
                'verbose_name': 'Группа по проф. ориентации',
                'verbose_name_plural': 'Группы по проф. ориентации',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schedule.bundle', verbose_name='Набор проб')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.CreateModel(
            name='TrainingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название цикла')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('schools', models.ManyToManyField(blank=True, related_name='train_cycles', to='users.School', verbose_name='Школы участники')),
            ],
            options={
                'verbose_name': 'Цикл проб',
                'verbose_name_plural': 'Циклы проб',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('zoom_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на конференцию (zoom)')),
                ('is_nonprofit', models.BooleanField(default=True, verbose_name='На безвозмездной основе')),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='education_centers.competence', verbose_name='Компетенция')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='education_centers.trainingprogram', verbose_name='Программа')),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedule.stream', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schedule.trainingcycle', verbose_name='Циклы'),
        ),
        migrations.AddField(
            model_name='stream',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stream', to='schedule.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='schedule.trainingcycle', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='edu_centers',
            field=models.ManyToManyField(blank=True, related_name='train_cycles', to='education_centers.EducationCenter', verbose_name='Центры обучения'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='voc_guid_bundle', to='education_centers.TrainingProgram', verbose_name='Программы пробы'),
        ),
    ]
