# Generated by Django 3.2.8 on 2022-03-14 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20220313_2228'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcycle',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='group',
        ),
        migrations.AddField(
            model_name='stream',
            name='attendance_limit',
            field=models.IntegerField(default=10, verbose_name='Максимальное кол-во участников'),
        ),
        migrations.AddField(
            model_name='stream',
            name='participants',
            field=models.ManyToManyField(related_name='training_groups', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='stream',
            name='schools',
            field=models.ManyToManyField(related_name='groups', to='users.School', verbose_name='Школы'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='TrainingCycle',
        ),
    ]
