# Generated by Django 3.2.8 on 2022-03-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220313_2228'),
        ('schedule', '0002_auto_20220314_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='schools',
        ),
        migrations.AddField(
            model_name='bundle',
            name='schools',
            field=models.ManyToManyField(related_name='groups', to='users.School', verbose_name='Школы'),
        ),
        migrations.AddField(
            model_name='stream',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
    ]
