# Generated by Django 3.2.8 on 2022-03-22 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0004_alter_timeslot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='Преподователь'),
        ),
    ]
