# Generated by Django 3.2.8 on 2022-03-22 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0010_educationcenter_trainers'),
        ('schedule', '0005_timeslot_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='slots', to='education_centers.workshop', verbose_name='Мастерская'),
        ),
    ]
