# Generated by Django 3.2.8 on 2022-03-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_timeslot_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='online',
            field=models.BooleanField(default=True, verbose_name='Онлайн'),
        ),
    ]
