# Generated by Django 3.2.8 on 2022-03-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0010_educationcenter_trainers'),
        ('schedule', '0007_timeslot_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='education_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='education_centers.educationcenter', verbose_name='Центр обучения'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
    ]
