# Generated by Django 3.2.8 on 2022-03-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20220322_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='program',
            new_name='programs',
        ),
    ]
