# Generated by Django 3.2.8 on 2022-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20220324_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='week_limit',
            field=models.IntegerField(default=2, verbose_name='Колво занятий в неделю'),
        ),
    ]
