# Generated by Django 3.2.8 on 2022-03-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компетенции')),
                ('is_ws', models.BooleanField(default=False, verbose_name='Worldskills')),
                ('block', models.CharField(blank=True, choices=[('IT', 'Информационные и коммуникационные технологии'), ('SR', 'Сфера услуг'), ('BD', 'Строительство и строительные технологии'), ('MF', 'Производство и инженерные технологии'), ('DS', 'Творчество и дизайн'), ('TR', 'Транспорт и логистика'), ('ED', 'Образование')], max_length=2, null=True, verbose_name='Блок')),
                ('competence_stage', models.CharField(blank=True, choices=[('MN', 'Основная'), ('PR', 'Презентационная')], max_length=2, null=True, verbose_name='Стадия')),
                ('competence_type', models.CharField(blank=True, choices=[('RU', 'WorldSkills Russia'), ('WSI', 'WorldSkills International'), ('WSE', 'WorldSkills Eurasia')], max_length=3, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='EducationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название организации')),
                ('contact_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='education_centers', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Центр обучения',
                'verbose_name_plural': 'Центры обучения',
            },
        ),
        migrations.CreateModel(
            name='FieldOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=240, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сфера деятельности',
                'verbose_name_plural': 'Сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=350, verbose_name='Адрес')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='education_centers.competence', verbose_name='Компетенция')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='education_centers.educationcenter', verbose_name='Центр обучения')),
            ],
            options={
                'verbose_name': 'Мастерская',
                'verbose_name_plural': 'Мастерские',
            },
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название программы')),
                ('program_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на программу')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='education_centers.competence', verbose_name='Компетенция')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='education_centers.educationcenter', verbose_name='Центр обучения')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='field_of_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='education_centers.fieldofactivity', verbose_name='Сфера деятельности'),
        ),
    ]
