# Generated by Django 3.2.8 on 2022-03-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220313_2228'),
        ('education_centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название программы')),
                ('program_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на программу')),
                ('attendance_limit', models.IntegerField(default=10, verbose_name='Максимальное кол-во участников')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='education_centers.competence', verbose_name='Компетенция')),
                ('disability_types', models.ManyToManyField(blank=True, to='users.DisabilityType', verbose_name='ОВЗ')),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='education_centers.educationcenter', verbose_name='Центр обучения')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.DeleteModel(
            name='EducationProgram',
        ),
    ]
