# Generated by Django 3.2.8 on 2022-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0002_auto_20220313_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Назывние критерия')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='criteria',
            field=models.ManyToManyField(to='education_centers.Criterion', verbose_name='Критерии'),
        ),
    ]
