# Generated by Django 3.2.8 on 2022-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0003_auto_20220320_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='description',
            field=models.CharField(max_length=240, null=True, verbose_name='Описание'),
        ),
    ]
