# Generated by Django 3.2.8 on 2022-03-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0005_alter_criterion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='description',
            field=models.CharField(max_length=440, null=True, verbose_name='Описание'),
        ),
    ]
