# Generated by Django 3.2.8 on 2022-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0006_alter_trainingprogram_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Назывние критерия'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
