# Generated by Django 3.2.8 on 2022-03-20 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_centers', '0007_auto_20220320_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='instructors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Преподователи'),
        ),
    ]
