# Generated by Django 3.2.8 on 2022-03-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_centers', '0010_educationcenter_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Описание'),
        ),
    ]
