# Generated by Django 3.2.8 on 2022-03-24 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_centers', '0011_workshop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='trainers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Преподователи'),
        ),
    ]
